// Generated by LiveScript 1.2.0
var fs, ref$, join, drop;
fs = require('fs');
ref$ = require("prelude-ls"), join = ref$.join, drop = ref$.drop;
fs.readFile("./cmpl_ls/merged.tsv", "utf-8", function(err, data){
  var changeDate, os;
  changeDate = function(it){
    return it.getFullYear() + "-" + (it.getMonth() + 1) + "-" + it.getDate();
  };
  os = "";
  data = data.split("\n").filter(function(it, i){
    var s, blank, ns;
    if (i > 0) {
      s = it.split("\t");
      blank = true;
      ns = s.map(function(d, j){
        if (j === 0) {
          return changeDate(new Date(d));
        }
        if (j > 0 && !(d === "-" || d === '')) {
          blank = false;
        }
        return d;
      });
      if (blank) {
        return false;
      } else {
        os += join("\t", ns) + "\n";
        return true;
      }
    } else {
      os += it + "\n";
      return true;
    }
  });
  return console.log(os);
});