// Generated by LiveScript 1.2.0
var fs, ref$, join, drop, dateFromDay, yr, nmLs, idx, reading;
fs = require('fs');
ref$ = require("prelude-ls"), join = ref$.join, drop = ref$.drop;
dateFromDay = function(y, d){
  var date;
  date = new Date(y, 0);
  return new Date(date.setDate(d));
};
yr = [1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014];
nmLs = ["evap", "precp", "solar", "temp_max", "temp_min", "temp"];
idx = 0;
reading = function(){
  return fs.readFile("./" + nmLs[idx] + ".tsv", "utf-8", function(err, data){
    var rslt;
    rslt = [];
    drop(1, data.split("\n")).map(function(it){
      var d;
      d = null;
      return it.split("\t").map(function(it, i){
        var dt;
        if (i === 0) {
          d = it;
        }
        dt = dateFromDay(yr[i - 1], d);
        return rslt.push({
          "d": dt,
          "v": it
        });
      });
    });
    return fs.writeFile("./cmpl_ls/" + nmLs[idx] + ".tsv", join("\n", rslt.sort(function(a, b){
      return a.d - b.d;
    }).map(function(it){
      return it.d + "\t" + it.v;
    })), function(it){
      if (it) {
        return console.log(it);
      } else {
        if (++idx < nmLs.length) {
          return reading();
        }
      }
    });
  });
};
reading();