// Generated by LiveScript 1.2.0
var async, action, res$, i$;
async = require('async');
res$ = [];
for (i$ = 1; i$ <= 12; ++i$) {
  res$.push((fn$.call(this, i$)));
}
action = res$;
async.series(action, function(err, data){
  return console.log(data);
});
function fn$(m){
  var i$, results$ = [];
  for (i$ = 1; i$ <= 12; ++i$) {
    results$.push((fn$.call(this, i$)));
  }
  return results$;
  function fn$(d){
    return function(p){
      return p(null, m + "-" + d);
    };
  }
}