// Generated by LiveScript 1.2.0
var request, cheerio, async, ref$, listsToObj, flatten, join, action, res$, i$;
request = require('request');
cheerio = require('cheerio');
async = require('async');
ref$ = require("prelude-ls"), listsToObj = ref$.listsToObj, flatten = ref$.flatten, join = ref$.join;
request = request.defaults({
  jar: true
});
res$ = [];
for (i$ = 1; i$ <= 9; ++i$) {
  res$.push((fn$.call(this, i$)));
}
action = res$;
async.series(action, function(err, data){
  return console.log(
  JSON.stringify(
  flatten(
  data)));
});
function fn$(i){
  return function(p){
    return request("http://www.cwb.gov.tw/V7/climate/30day/Data/46692_2014060" + i + ".htm", function(err, res, body){
      var dayResult, $, row, s;
      dayResult = [];
      $ = cheerio.load(body);
      row = $("table table tr").first().next();
      s = "";
      while (row.text()) {
        dayResult.push(
        row.children().map(fn$));
        row = row.next();
      }
      return p(null, dayResult);
      function fn$(){
        return this.text().replace("\r\n", "");
      }
    });
  };
}